### ISSUE TITLE
Some really upsetting stuff

### ISSUE THREAD

**Issue by Shamshu1** [syyePhenomenol/HollowKnight.VanillaMapMod#3] opened 2022-11-12 17:32 UTC
Hey, I dont think it should works like that
![Снимок экрана от 2022-11-12 19-56-05](https://user-images.githubusercontent.com/88609547/201485798-a03f6c59-f44e-47ca-8575-24107ae20888.png)
it happens when I open full map and bench after that (disappears only after next map openning)
Also I have a problem with some pins dont disappear (eg this charm)
![Снимок экрана от 2022-11-12 20-01-13](https://user-images.githubusercontent.com/88609547/201485944-244026e4-a78e-4ed0-91c4-2c045bc9bc31.png)
![Снимок экрана от 2022-11-12 20-01-33](https://user-images.githubusercontent.com/88609547/201485957-6f825c1b-8424-4ed1-b3f6-bd251b502cb3.png)
[ModLog.txt](https://github.com/syyePhenomenol/HollowKnight.VanillaMapMod/files/9995528/ModLog.txt)
Thanks in advance <3

**Comment by syyePhenomenol** [comment] 2022-11-12 23:29
Does the problem still remain if you uninstall LoreMaster?

**Comment by Shamshu1** [comment] 2022-11-12 23:32
Yeap

**Comment by syyePhenomenol** [comment] 2022-11-12 23:38
Does the button menu on the pause screen still show up? Can you interact with it?

Could you try setting the log level in ModdingApi.GlobalSettings.json to 1, open the game, get back to the same issue, and send the ModLog again? Thanks

**Comment by Shamshu1** [comment] 2022-11-12 23:53
> Yeap

*on the same file, with fresh one it doesnt appear but problem with some objects (charm, mimic etc) is still there
** ̶h̶o̶w̶e̶v̶e̶r̶ ̶t̶h̶a̶t̶ ̶h̶a̶p̶p̶e̶n̶e̶d̶ ̶a̶f̶t̶e̶r̶ ̶2̶+̶h̶ ̶i̶n̶ ̶g̶a̶m̶e̶,̶ ̶a̶f̶t̶e̶r̶ ̶b̶e̶n̶c̶h̶ ̶i̶n̶ ̶w̶a̶t̶e̶r̶w̶a̶y̶s̶,̶ ̶s̶o̶..    ||    a̶f̶t̶e̶r̶ ̶"̶s̶e̶t̶t̶i̶n̶g̶ ̶t̶h̶e̶ ̶l̶o̶g̶ ̶l̶e̶v̶e̶l̶ ̶i̶n̶ ̶M̶o̶d̶d̶i̶n̶g̶A̶p̶i̶.̶G̶l̶o̶b̶a̶l̶S̶e̶t̶t̶i̶n̶g̶s̶.̶j̶s̶o̶n̶ ̶t̶o̶ ̶1̶"̶ ̶i̶t̶ ̶d̶i̶s̶a̶p̶p̶e̶a̶r̶s̶ ||  :/ sorry, but with reopening files and game it changes, now like that:
![Снимок экрана от 2022-11-13 02-48-54](https://user-images.githubusercontent.com/88609547/201499076-97314272-4063-4072-8dfd-a6c8f954605f.png)
[ModLog.txt](https://github.com/syyePhenomenol/HollowKnight.VanillaMapMod/files/9996245/ModLog.txt)

**Comment by syyePhenomenol** [comment] 2022-11-13 00:09
To test if this is a problem specific to your current save, could you start a new game, unlock the full map, open it, then rest at a bench? Thanks

**Comment by Shamshu1** [comment] 2022-11-13 00:15
> *on the same file, with fresh one it doesnt appear but problem with some objects (charm, mimic etc) is still there 

nothing weird happens

**Comment by syyePhenomenol** [comment] 2022-11-13 00:37
Oh I see.

I'm still not sure what is causing this. Next would you be able to send your save files? userX.json and userX.modded.json

**Comment by Shamshu1** [comment] 2022-11-13 05:57
[user.zip](https://github.com/syyePhenomenol/HollowKnight.VanillaMapMod/files/9996578/user.zip)

**Comment by syyePhenomenol** [comment] 2022-11-13 08:19
I have found and fixed the problems associated with these pins not disappearing:
- Dashmaster
- Dream Wielder
- Mimics

Did you encounter any other pins that didn't go away?

I still don't know why the original problem occurs, but at least it seems only limited to that one save.

**Comment by Shamshu1** [comment] 2022-11-13 08:38
> Did you encounter any other pins that didn't go away?
No

**Comment by Shamshu1** [comment] 2022-11-13 19:42
I got this in a new file started after mod update о_О (w/o loremaster)
![Снимок экрана от 2022-11-13 22-21-14](https://user-images.githubusercontent.com/88609547/201540435-b4e8463f-d4f6-460f-8bd9-0ca99cffc666.png)
[ModLog.txt](https://github.com/syyePhenomenol/HollowKnight.VanillaMapMod/files/9998041/ModLog.txt)
and I got the trigger - it happens after collecting all maps & quill (Im not sure if its matter doing it by debug mode or in default way)
*btw mimics and charms now work fine, thanks)

**Comment by syyePhenomenol** [comment] 2022-11-13 23:32
Some things to try:
In the DebugModData folder, delete the save states corresponding to the file you are currently on

Delete all mods (including global settings) and reinstall them

The problem is most likely not because of VanillaMapMod.

**Comment by syyePhenomenol** [comment] 2022-11-13 23:33
One last thing to try is to delete all userX files corresponding to the current save

**Comment by Shamshu1** [comment] 2022-11-14 06:26
I deleted everything corresponding to hollow knight, reinstalled just the game itself and VanillaMapMod, load into the game, quit out, edited the save (.bak) to have maps & quill and thats it 
![image](https://user-images.githubusercontent.com/88609547/201589391-3ff0f0d3-c662-4ddf-82f3-2ff2a2b48f54.png)

**Comment by syyePhenomenol** [comment] 2022-11-14 09:49
Thanks for your patience so far. I finally seem to have reproduced the issue and found what is causing it.

**Comment by syyePhenomenol** [comment] 2022-11-14 09:56
Please avoid setting "mapAllRooms" to true in the player data. In fact you might not need to edit anything at all.

If you want to see the full map while using VanillaMapMod, all you need to do is to click on the "Mode" button in the pause menu to switch to "Full Map".

**Comment by Shamshu1** [comment] 2022-11-14 10:14
Oh, the very first time I couldn't get all maps (to get rid of their pins) in default way because of other mod, so I did it by debug and all the times after, I was doing it, cause its obviously faster to test. 
So in normal playthrough it can't happen?

**Comment by syyePhenomenol** [comment] 2022-11-14 10:17
Yep, it won't be set to true unless you edit the save yourself.

**Comment by Shamshu1** [comment] 2022-11-16 06:30
Hello once again <3. Shopkeeper's key pin doesnt go away and it seems that it is happening because this pin has a check like 'true if it is in inventory' = pin came back after Sly dialogue

**Comment by syyePhenomenol** [comment] 2022-11-16 09:27
Hi, thanks for pointing this out. This should be fixed in the next update of MapChanger

**Closed** 2022-12-25 22:37 UTC
